//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Benedek\Desktop\Dipterv_src\DbgDsl\CodeProcessor\Grammar\DbgGrammar.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CodeProcessor.Grammar {
#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DbgGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IDbgGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] DbgGrammarParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementList([NotNull] DbgGrammarParser.StatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.definitionStatementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinitionStatementList([NotNull] DbgGrammarParser.DefinitionStatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DbgGrammarParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.definitionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinitionStatement([NotNull] DbgGrammarParser.DefinitionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.commandDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommandDefinition([NotNull] DbgGrammarParser.CommandDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.cardDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCardDefinition([NotNull] DbgGrammarParser.CardDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.varDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDefinition([NotNull] DbgGrammarParser.VarDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] DbgGrammarParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] DbgGrammarParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.commandDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommandDeclaration([NotNull] DbgGrammarParser.CommandDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.propertyDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyDefinition([NotNull] DbgGrammarParser.PropertyDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.argumentDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentDeclaration([NotNull] DbgGrammarParser.ArgumentDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDefinition([NotNull] DbgGrammarParser.TypeDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] DbgGrammarParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] DbgGrammarParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarRef([NotNull] DbgGrammarParser.VarRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.varMemberPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarMemberPath([NotNull] DbgGrammarParser.VarMemberPathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.numericExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericExpression([NotNull] DbgGrammarParser.NumericExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.booleanExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanExpression([NotNull] DbgGrammarParser.BooleanExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.relationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationExpression([NotNull] DbgGrammarParser.RelationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.enumIsExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumIsExpression([NotNull] DbgGrammarParser.EnumIsExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.listHasExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListHasExpression([NotNull] DbgGrammarParser.ListHasExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.numberPredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberPredicate([NotNull] DbgGrammarParser.NumberPredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.cardPredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCardPredicate([NotNull] DbgGrammarParser.CardPredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.enumLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumLiteral([NotNull] DbgGrammarParser.EnumLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.takeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTakeExpression([NotNull] DbgGrammarParser.TakeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DbgGrammarParser.putExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPutExpression([NotNull] DbgGrammarParser.PutExpressionContext context);
}
} // namespace CodeProcessor.Grammar
